feat: 1st Job finished (testing it right now)

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,4 +22,14 @@ jobs:
             - uses: actions/checkout@v4
             - run: |
                 check.sh $(pwd) $(pwd)
-                echo coding-style-reports.log
+                CODING_STYLE_ERRORS=$coding-style-reports.log
+                for ERRORS in $CODING_STYLE_ERRORS; do
+                    array=(echo $ERRORS)
+                    echo "::error file=${array[i]#./},title=${array[3]#./}, the followed coding style errors has been detected: ${array[2]#./}::${array[4]#./}"
+                done
+                if [[ -n $CODING_STYLE_ERRORS ]]
+                then
+                    exit 1
+                else
+                    echo Clean code, no coding style errors detected
+                fi
